version: "3.3"

services:
  app:
    container_name: app
    hostname: api
    image: sdg-app:latest
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./home:/usr/share/nginx/html
      - ./nginx.conf:/nginx/nginx.conf
    ports:
      - "8089:80"
    links:
      - api
    depends_on:
      - api
    networks:
      - sdg

  api:
    container_name: api
    hostname: api
    image: sdg-api:latest
    restart: always
    build:
      context: ./api
      args:
        API_PORT: ${API_PORT}
        NODE_ENV: ${NODE_ENV}
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - sdg

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    hostname: mongo
    env_file:
      - .env
    networks:
      - sdg

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - sdg

volumes:
  mongodata:

networks:
  sdg:
