version: '3.7'

services:

  research:
    container_name: sdg-goals
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
