version: '3.7'

services:

  research:
    container_name: nmbu-sdg
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=development
